// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
public class OwnerPage {
    private IWebDriver driver;

    public OwnerPage(IWebDriver driver) {
        this.driver = driver;
    }
    public IWebElement ownerTab => driver.FindElement(By.CssSelector(".ownerTab"));
    public IWebElement ownerTabAddNewDropdown => driver.FindElement(By.CssSelector(".open li:nth-child(2) span:nth-child(2)"));
    public IWebElement firstNameField => driver.FindElement(By.Id("firstName"));
    public IWebElement lastNameField => driver.FindElement(By.Id("lastName"));
    public IWebElement addressField => driver.FindElement(By.Id("address"));
    public IWebElement cityField => driver.FindElement(By.Id("city"));
    public IWebElement telephoneField => driver.FindElement(By.Id("telephone"));
    public IWebElement addOwnerButton => driver.FindElement(By.CssSelector(".addOwner"));
}