// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class NavigationTests:TestBase {
  [Test]
  public void ownerTabTestCase() {
    var ownerPage = new OwnerPage(driver);
    ownerPage.ownerTab.Click();
    ownerPage.ownerTabAddNewDropdown.Click();
  }
  [Test]
  public void veterinarianTabTestCase() {
    var veterinarianPage = new VeterinarianPage(driver);
    veterinarianPage.veterinarianTab.Click();
    veterinarianPage.veterinarianTabAddNewDropdown.Click();
  }
  [Test]
  public void petTypeTabTestCase() {
    var petTypePage = new PetTypePage(driver);
    petTypePage.petTypeTab.Click();
  }
  [Test]
  public void specialtiesTabTestCase() {
    var specialtiesPage = new SpecialtiesPage(driver);
    specialtiesPage.specialtiesTab.Click();
  }
}
