// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class OwnerTests:TestBase {
  [Test]
  public void addOwnerTestCase() {
    var ownerPage = new OwnerPage(driver);
    ownerPage.ownerTab.Click();
    ownerPage.ownerTabAddNewDropdown.Click();
    ownerPage.firstNameField.Click();
    ownerPage.firstNameField.SendKeys("Max");
    ownerPage.lastNameField.Click();
    ownerPage.lastNameField.SendKeys("Willing");
    ownerPage.addressField.Click();
    ownerPage.addressField.SendKeys("6812 20th Ave, Brooklyn, NY 11204");
    ownerPage.cityField.Click();
    ownerPage.cityField.SendKeys("New York");
    ownerPage.telephoneField.Click();
    ownerPage.telephoneField.SendKeys("1718232111");
    ownerPage.addOwnerButton.Click();
  }
}
