// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class PetTypeTests:TestBase {
  [Test]
  public void addPetTypeTestCase() {
    var petTypePage = new PetTypePage(driver);
    petTypePage.petTypeTab.Click();
    petTypePage.addPetTypeButton.Click();
    petTypePage.nameField.Click();
    petTypePage.nameField.SendKeys("racoon");
    petTypePage.savePetTypeButton.Click();
  }
  [Test]
  public void editPetTypeTestCase() {
    var petTypePage = new PetTypePage(driver);
    petTypePage.petTypeTab.Click();
    Wait();
    petTypePage.editPetTypeButton.Click();
    petTypePage.nameField.Click();
    petTypePage.nameField.SendKeys("mouse");
    petTypePage.updatePetTypeButton.Click();
    driver.Close();
  }
  [Test]
  public void deletePetTypeTestCase() {
    var petTypePage = new PetTypePage(driver);
    petTypePage.petTypeTab.Click();
    Wait();
    Assert.That(petTypePage.getThirdPetTypeElementValue, Is.EqualTo("lizard"));
    petTypePage.deletePetTypeButton.Click();
  }
  [Test]
  public void homeButtonTestCase() {
    var petTypePage = new PetTypePage(driver);
    petTypePage.petTypeTab.Click();
    petTypePage.returnHomeButton.Click();
  }
}
