// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class VeterinarianTests:TestBase {
  [Test]
  public void addVeterinarianTestCase() {
    var newVeterinarianPage = new NewVeterinarianPage(driver);
    driver.FindElement(By.CssSelector(".vetsTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(2) > a")).Click();
    Wait();
    newVeterinarianPage.firstNameField.Click();
    newVeterinarianPage.firstNameField.SendKeys("Karen");
    newVeterinarianPage.firstNameField.Click();
    newVeterinarianPage.firstNameField.SendKeys("Berkly");
    newVeterinarianPage.selectSpecialty("dentistry");
    newVeterinarianPage.addVeterinarianButton.Click();
  }
}
