// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class VeterinarianTests:TestBase {
  [Test]
  public void addVeterinarianTestCase() {
    var veterinarianPage = new VeterinarianPage(driver);
    veterinarianPage.veterinarianTab.Click();
    veterinarianPage.veterinarianTabAddNewDropdown.Click();
    Wait();
    veterinarianPage.firstNameField.Click();
    veterinarianPage.firstNameField.SendKeys("Karen");
    veterinarianPage.firstNameField.Click();
    veterinarianPage.firstNameField.SendKeys("Berkly");
    veterinarianPage.selectSpecialty("dentistry");
    veterinarianPage.addVeterinarianButton.Click();
  }
}
