// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DefaultSuiteTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testCase1Modified() {
    driver.Navigate().GoToUrl("http://20.50.171.10:8080//");
    driver.FindElement(By.CssSelector(".ownerTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(1) > a")).Click();
    driver.FindElement(By.CssSelector(".petOwner:nth-child(1) a")).Click();
    driver.FindElement(By.CssSelector(".addNewPet")).Click();
    driver.FindElement(By.Id("name")).Click();
    driver.FindElement(By.Id("name")).SendKeys("Cherry");
    driver.FindElement(By.CssSelector(".mat-datepicker-toggle-default-icon")).Click();
    driver.FindElement(By.CssSelector(".mat-calendar-period-button > .mat-button-wrapper")).Click();
    driver.FindElement(By.CssSelector(".ng-star-inserted:nth-child(1) > .mat-calendar-body-cell:nth-child(2) > .mat-calendar-body-cell-content")).Click();
    driver.FindElement(By.CssSelector(".ng-star-inserted:nth-child(4) > .mat-calendar-body-cell:nth-child(3) > .mat-calendar-body-cell-content")).Click();
    driver.FindElement(By.CssSelector(".ng-star-inserted:nth-child(4) > .mat-calendar-body-cell:nth-child(2) > .mat-calendar-body-cell-content")).Click();
    driver.FindElement(By.Id("type")).Click();
    {
      var dropdown = driver.FindElement(By.Id("type"));
      dropdown.FindElement(By.XPath("//option[. = 'lizard']")).Click();
    }
    driver.FindElement(By.CssSelector(".savePet")).Click();
  }
  [Test]
  public void testCase2Modified() {
    driver.Navigate().GoToUrl("http://20.50.171.10:8080//");
    driver.FindElement(By.CssSelector(".ownerTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(1) span:nth-child(2)")).Click();
    driver.FindElement(By.CssSelector(".petOwner:nth-child(1) a")).Click();
    driver.FindElement(By.CssSelector(".addNewVisit")).Click();
    driver.FindElement(By.CssSelector("path")).Click();
    driver.FindElement(By.CssSelector(".ng-star-inserted:nth-child(5) > .mat-calendar-body-cell:nth-child(4) > .mat-calendar-body-cell-content")).Click();
    driver.FindElement(By.Id("description")).Click();
    driver.FindElement(By.Id("description")).SendKeys("New visit");
    driver.FindElement(By.CssSelector(".addVisit")).Click();
  }
  [Test]
  public void testCase3Modified() {
    driver.Navigate().GoToUrl("http://20.50.171.10:8080//");
    driver.FindElement(By.CssSelector(".ownerTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(1) > a")).Click();
    driver.FindElement(By.CssSelector(".petOwner:nth-child(1) a")).Click();
    driver.FindElement(By.CssSelector("app-pet-list:nth-child(1) .deletePet")).Click();
  }
  [Test]
  public void testCase4Modified() {
    driver.Navigate().GoToUrl("http://20.50.171.10:8080//");
    driver.FindElement(By.CssSelector(".ownerTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(1) > a")).Click();
    driver.FindElement(By.CssSelector(".petOwner:nth-child(1) a")).Click();
    driver.FindElement(By.CssSelector("app-pet-list:nth-child(1) .editPet")).Click();
    driver.FindElement(By.Id("name")).Click();
    driver.FindElement(By.Id("name")).SendKeys("Peaches");
    driver.FindElement(By.CssSelector("path")).Click();
    driver.FindElement(By.CssSelector(".mat-calendar-period-button > .mat-button-wrapper")).Click();
    driver.FindElement(By.CssSelector(".ng-star-inserted:nth-child(1) > .mat-calendar-body-cell:nth-child(3) > .mat-calendar-body-cell-content")).Click();
    driver.FindElement(By.CssSelector(".ng-star-inserted:nth-child(2) > .mat-calendar-body-cell:nth-child(4) > .mat-calendar-body-cell-content")).Click();
    driver.FindElement(By.CssSelector(".ng-star-inserted:nth-child(3) > .mat-calendar-body-cell:nth-child(4) > .mat-calendar-body-cell-content")).Click();
    driver.FindElement(By.Id("type")).Click();
    {
      var dropdown = driver.FindElement(By.Id("type"));
      dropdown.FindElement(By.XPath("//option[. = 'snake']")).Click();
    }
    driver.FindElement(By.CssSelector(".updatePet")).Click();
  }
}
