// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class PetClinicSuiteTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testCase1() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.FindElement(By.CssSelector(".ownerTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(1) > a")).Click();
  }
  [Test]
  public void testCase2() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.FindElement(By.CssSelector(".vetsTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(1) > a")).Click();
  }
  [Test]
  public void testCase3() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.FindElement(By.CssSelector("li:nth-child(4) span:nth-child(2)")).Click();
  }
  [Test]
  public void testCase4() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.FindElement(By.CssSelector("li:nth-child(5) > a")).Click();
  }
  [Test]
  public void testCase5() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.FindElement(By.CssSelector(".ownerTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(2) span:nth-child(2)")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Max");
    driver.FindElement(By.Id("lastName")).Click();
    driver.FindElement(By.Id("lastName")).SendKeys("Willing");
    driver.FindElement(By.Id("address")).Click();
    driver.FindElement(By.Id("address")).SendKeys("6812 20th Ave, Brooklyn, NY 11204");
    driver.FindElement(By.Id("city")).Click();
    driver.FindElement(By.Id("city")).SendKeys("New York");
    driver.FindElement(By.Id("telephone")).Click();
    driver.FindElement(By.Id("telephone")).SendKeys("1718232111");
    driver.FindElement(By.CssSelector(".addOwner")).Click();
  }
  [Test]
  public void testCase6() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.FindElement(By.CssSelector(".vetsTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(2) > a")).Click();
    driver.FindElement(By.Id("firstName")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("Karen");
    driver.FindElement(By.Id("lastName")).Click();
    driver.FindElement(By.Id("lastName")).SendKeys("Berkly");
    driver.FindElement(By.Id("specialties")).Click();
    {
      var dropdown = driver.FindElement(By.Id("specialties"));
      dropdown.FindElement(By.XPath("//option[. = 'dentistry']")).Click();
    }
    driver.FindElement(By.CssSelector(".saveVet")).Click();
  }
  [Test]
  public void testCase7() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.FindElement(By.CssSelector("li:nth-child(4) > a")).Click();
    driver.FindElement(By.CssSelector(".addPet")).Click();
    driver.FindElement(By.Id("name")).Click();
    driver.FindElement(By.Id("name")).SendKeys("racoon");
    driver.FindElement(By.CssSelector(".saveType")).Click();
  }
  [Test]
  public void testCase8() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.FindElement(By.CssSelector("li:nth-child(4) span:nth-child(2)")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(4) .editPet")).Click();
    driver.FindElement(By.Id("name")).Click();
    driver.FindElement(By.Id("name")).SendKeys("mouse");
    driver.FindElement(By.CssSelector(".updatePetType")).Click();
    driver.Close();
  }
  [Test]
  public void testCase9() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.FindElement(By.CssSelector("li:nth-child(4) span:nth-child(2)")).Click();
    {
      string value = driver.FindElement(By.Id("2")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("lizard"));
    }
    driver.FindElement(By.CssSelector("tr:nth-child(3) .deletePet")).Click();
  }
  [Test]
  public void testCase10() {
    driver.Navigate().GoToUrl("http://20.82.57.125:8080/");
    driver.FindElement(By.CssSelector("li:nth-child(4) > a")).Click();
    driver.FindElement(By.CssSelector(".returnHome")).Click();
  }
}
